require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'

Style/DoubleNegation:
  Enabled: no

Style/Documentation:
  Enabled: yes
  Exclude:
    - 'db/**/*.rb'
    - 'config/**/*.rb'
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Enabled: yes
  Exclude:
    - 'db/migrate/20220120041607_devise_token_auth_create_users.rb'

Metrics/MethodLength:
  Enabled: yes
  Exclude:
    - 'db/migrate/20220120041607_devise_token_auth_create_users.rb'

Metrics/CyclomaticComplexity:
  Enabled: yes

Metrics/PerceivedComplexity:
  Enabled: yes

Metrics/ClassLength:
  Enabled: yes

Naming/AccessorMethodName:
  Enabled: yes

Layout/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Max: 3

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/LetSetup:
  Enabled: no
